# Generated by Django 5.0.3 on 2024-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.PositiveIntegerField()),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('domaine_etude', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
